/*
 * This program generates an ethernetframe of the following form:
 *
 *  ##############################################################
 *  # dst addr | src addr | payloadproto | ------ payload ------ #
 *  ##############################################################
 *
 *  It takes the destination address, payload protocol and payload as
 *  parameters and sends exactly one ethernetframe to the target.
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <fcntl.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <net/ethernet.h> /* the L2 protocols */
#include <netinet/in.h>
#include <linux/if_arp.h>

int main(int argc,char** argv)
{
  int packet_socket; // the socketdescriptor
  struct ifreq etherreq; // used for ioctl
  struct sockaddr_ll ll; // network layer 2 structure
  unsigned char dst[6];
  unsigned char buf[ETH_FRAME_LEN]; // ethernet framebuffer
  unsigned flength;
  int fd;

  if (argc != 5)
  {
    printf(
      "usage: RAW_Packet <iface> <destination> <payloadproto> <payloadfile>\n"
    );
    return EXIT_FAILURE;
  }

  if(strlen(argv[1]) > IFNAMSIZ)
  {
    printf("wrong interface\n");
    return EXIT_FAILURE;
  }

  // copy the interface string into the interface request structure
  strncpy(etherreq.ifr_name,argv[1],IFNAMSIZ);

  if(strlen(argv[2]) != 17)
  {
    printf("destination: xx:xx:xx:xx:xx:xx\n");
    return EXIT_FAILURE;
  }
  
  if(strncmp(argv[3], "0x", 2) > 0) {
    printf("payloadproto should start with \"0x\"\n");
    return EXIT_FAILURE;
  }

  char *tok;
  if((tok = strtok(argv[2],":")) != NULL)
  {
    dst[0] = (char) strtol(tok,NULL,16);
    int i = 1;
    while((tok = strtok(NULL,":")) != NULL)
    {
      dst[i] = (char) strtol(tok,NULL,16);
      i++;
    }
  }
  else
  {
    printf("destination: xx:xx:xx:xx:xx:xx\n");
    return EXIT_FAILURE;
  }

  // protocol types are defined in linux/if_ether.h
  int proto = strtol(argv[3],NULL,16);

  if((fd = open(argv[4],O_RDONLY)) < 0)
  {
    perror("open error");
    return EXIT_FAILURE;
  }

  // determine length of the payload file
  if ((flength = (unsigned) lseek(fd,0,SEEK_END)) > (ETH_FRAME_LEN - ETH_HLEN))
  {
    printf("file is too large for one frame\n");
    close(fd);
    return EXIT_FAILURE;
  }

  lseek(fd,0,SEEK_SET);

  if(read(fd,buf,flength) < 0)
  {
    perror("read error");
    close(fd);
    return EXIT_FAILURE;
  }

  close(fd);

  /*
   * A layer 2 socket is created (PF_PACKET).
   * The header will be generated by the OS (SOCK_DGRAM).
   */
  if ((packet_socket = socket(PF_PACKET,SOCK_DGRAM,htons(ETH_P_ALL))) < 0)
  {
    perror("socket error");
    return EXIT_FAILURE;
  }

  ll.sll_family = PF_PACKET;
  ll.sll_protocol = htons(proto); // protocol type of the payload
  
  /*
   * We need the interface id of our ethernet device. IOCTL fills our ifreq 
   * structure with the needed values.
   */
  if(ioctl(packet_socket,SIOCGIFINDEX, &etherreq) < 0)
  {
    perror("ioctl error");
    close(packet_socket);
    return EXIT_FAILURE;
  }

  ll.sll_ifindex = etherreq.ifr_ifindex; // interface id
  
  ll.sll_halen = (char) 0x06; // length of the physical address

  memcpy(&ll.sll_addr,&dst,6); // physical address of the target

  if(sendto(packet_socket,&buf,flength,0,(struct sockaddr*) &ll,sizeof(ll)) < 0)
  {
    perror("send error");
    close(packet_socket);
    return EXIT_FAILURE;
  }

  close(packet_socket);
  return EXIT_SUCCESS;
}
